- name: Create Differential backup
  hosts: postgres_db
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Create Differential backup
      ansible.builtin.shell: |
        pgbackrest --stanza=demo --type=differential backup
      tags:
        - create_differential_backup
