- name: Create Full backup
  hosts: postgres_db
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Create Full backup
      ansible.builtin.shell: |
        pgbackrest --stanza=netflix_shows --type=full backup
      tags:
        - create_full_backup
